// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcYmkP3J8kzlw7lvDTIy3yWEPLE5MMRg',
    appId: '1:112336849012:web:9a3ebfe4ebea4845a2a921',
    messagingSenderId: '112336849012',
    projectId: 'chatapp-7531e',
    authDomain: 'chatapp-7531e.firebaseapp.com',
    storageBucket: 'chatapp-7531e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvK91LrLGY56LZ4lRP6k6-JmTMRC2h41U',
    appId: '1:112336849012:android:386ad3e5a47e9664a2a921',
    messagingSenderId: '112336849012',
    projectId: 'chatapp-7531e',
    storageBucket: 'chatapp-7531e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcYmkP3J8kzlw7lvDTIy3yWEPLE5MMRg',
    appId: '1:112336849012:web:0c98bf6d5b939bc7a2a921',
    messagingSenderId: '112336849012',
    projectId: 'chatapp-7531e',
    authDomain: 'chatapp-7531e.firebaseapp.com',
    storageBucket: 'chatapp-7531e.appspot.com',
  );
}
